//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeStructures.Design.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeStructures.Design.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 W44X335,5.5,38,3
        ///W44X290,5.5,38,2.8125
        ///W44X262,5.5,38,2.625
        ///W44X230,5.5,38,2.4375
        ///W40X655,7.5,34,4.8125
        ///W40X593,7.5,34,4.5
        ///W40X503,7.5,34,4
        ///W40X431,7.5,34,3.625
        ///W40X397,7.5,34,3.5
        ///W40X372,7.5,34,3.3125
        ///W40X362,7.5,34,3.25
        ///W40X324,7.5,34,3.0625
        ///W40X297,7.5,34,2.9375
        ///W40X277,7.5,34,2.875
        ///W40X249,7.5,34,2.6875
        ///W40X215,7.5,34,2.5
        ///W40X199,7.5,34,2.3125
        ///W40X392,7.5,34,3.8125
        ///W40X331,7.5,34,3.375
        ///W40X327,7.5,34,3.375
        ///W40X294,7.5,34,3.1875
        ///W40X278,7.5,34,3.0625
        ///W40X264,7.5,34,3
        ///W40X235,7.5,34,2.875
        ///W40X211,7.5,34,2 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GBShapeDatabaseDetailingImperial {
            get {
                return ResourceManager.GetString("GBShapeDatabaseDetailingImperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShapeId,Type,W,A,d,Ht,h,OD,bf,B,b,ID,tw,tf,t,tnom,tdes,kdes,x,y,eo,xp,yp,Ix,Zx,Sx,rx,Iy,Zy,Sy,ry,Iz,rz,Sz,J,Cw,C,Wno,Sw1,Sw2,Sw3,Qf,Qw,ro,H,tanAlpha,Qs,Iw,zA,zB,zC,wA,wB,wC,SwA,SwB,SwC,SzA,SzB,SzC,rts,ho,PA,PB
        ///W44X335,W,335,98.5,44.0,0,0,0,15.9,0,0,0,1.03,1.77,0,0,0,2.56,0,0,0,0,0,31100,1620,1410,17.8,1200,236,150,3.49,0,0,0,74.7,535000,0,168,1180,0,0,278,805,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.24,42.2,132,148
        ///W44X290,W,290,85.4,43.6,0,0,0,15.8,0,0,0,0.865,1.58,0,0,0,2.36,0,0,0,0,0,27000,1410,1240,17.8,1040 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GBShapeDatabaseImperial {
            get {
                return ResourceManager.GetString("GBShapeDatabaseImperial", resourceCulture);
            }
        }
    }
}
